# Generated by Django 3.0.3 on 2020-03-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(auto_now=True)),
                ('documento', models.IntegerField(choices=[(1, 'CEDULA DE IDENTIDAD'), (2, 'PASAPORTE'), (3, 'CERTIFICADO DE NACIMIENTO')], default=1)),
                ('nro_documento', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ocupacion', models.CharField(blank=True, max_length=50)),
                ('codigo', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
