# Generated by Django 3.0.3 on 2020-03-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguro', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('fecha_consulta', models.DateField(auto_now=True)),
                ('hora_inicio', models.TimeField(auto_now=True)),
                ('tipo', models.IntegerField(choices=[('PARTICULAR', 'PARTICULAR'), ('SEGURO', 'SEGURO')], default=0)),
                ('procedencia', models.CharField(blank=True, max_length=100)),
                ('matricula', models.CharField(blank=True, max_length=100)),
                ('tipo_beneficiario', models.IntegerField(choices=[(0, 'BENEFICIARIO'), (1, 'ACTIVO'), (2, 'RENTISTA')], default=0)),
                ('motivo', models.TextField(blank=True)),
                ('antecedentes', models.TextField(blank=True)),
                ('atendido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguro.Seguro')),
            ],
        ),
    ]
